const ROLES = Object.freeze({
  ADMIN: "admin",
  DOCTOR: "doctor",
  NURSE: "nurse",
  SECRETARY: "secretary",
  STAFF: "staff",
  PARENT: "parent",
});

const STAFF_ROLES = [
  ROLES.ADMIN,
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.SECRETARY,
  ROLES.STAFF,
];

const ALLOWED_STAFF_CREATION_ROLES = [
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.SECRETARY,
  ROLES.STAFF,
];

const MEDICAL_ROLES = [ROLES.ADMIN, ROLES.DOCTOR, ROLES.NURSE];
const FRONT_DESK_ROLES = [ROLES.ADMIN, ROLES.SECRETARY, ROLES.STAFF, ROLES.NURSE];

module.exports = {
  ROLES,
  STAFF_ROLES,
  ALLOWED_STAFF_CREATION_ROLES,
  MEDICAL_ROLES,
  FRONT_DESK_ROLES,
};
