const ROLES = Object.freeze({
  ADMIN: "admin",
  DOCTOR: "doctor",
  NURSE: "nurse",
  SECRETARY: "secretary",
  STAFF: "staff",
  PARENT: "parent",
});

const STAFF_ROLES = [
  ROLES.ADMIN,
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.SECRETARY,
  ROLES.STAFF,
];

const OPERATIONS_ROLES = [
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.SECRETARY,
  ROLES.STAFF,
];

const MANAGEABLE_STAFF_ROLES = [
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.SECRETARY,
  ROLES.STAFF,
];

const CREATABLE_STAFF_ROLES = [
  ROLES.DOCTOR,
  ROLES.SECRETARY,
];

const MEDICAL_ROLES = [ROLES.DOCTOR, ROLES.NURSE];
const EMR_WRITE_ROLES = [ROLES.DOCTOR];
const FRONT_DESK_ROLES = [ROLES.ADMIN, ROLES.SECRETARY, ROLES.STAFF, ROLES.NURSE];
const PATIENT_CREATION_ROLES = [ROLES.SECRETARY, ROLES.STAFF, ROLES.NURSE];
const PATIENT_APPROVAL_ROLES = [
  ROLES.ADMIN,
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.SECRETARY,
  ROLES.STAFF,
];
const APPOINTMENT_CREATION_ROLES = [
  ROLES.DOCTOR,
  ROLES.SECRETARY,
  ROLES.STAFF,
];
const APPOINTMENT_EDIT_ROLES = [
  ROLES.DOCTOR,
  ROLES.NURSE,
  ROLES.SECRETARY,
  ROLES.STAFF,
];

module.exports = {
  ROLES,
  STAFF_ROLES,
  OPERATIONS_ROLES,
  MANAGEABLE_STAFF_ROLES,
  CREATABLE_STAFF_ROLES,
  MEDICAL_ROLES,
  EMR_WRITE_ROLES,
  FRONT_DESK_ROLES,
  PATIENT_CREATION_ROLES,
  PATIENT_APPROVAL_ROLES,
  APPOINTMENT_CREATION_ROLES,
  APPOINTMENT_EDIT_ROLES,
};
