export const ROLES = {
  ADMIN: "admin",
  DOCTOR: "doctor",
  SECRETARY: "secretary",
  STAFF: "staff",
  PARENT: "parent",
};

export const STAFF_ROLES = [
  ROLES.ADMIN,
  ROLES.DOCTOR,
  ROLES.SECRETARY,
  ROLES.STAFF,
];

export const OPERATIONS_ROLES = [
  ROLES.DOCTOR,
  ROLES.SECRETARY,
  ROLES.STAFF,
];

export const MEDICAL_ROLES = [ROLES.DOCTOR];
export const EMR_WRITE_ROLES = [ROLES.DOCTOR];
export const FRONT_DESK_ROLES = [ROLES.ADMIN, ROLES.SECRETARY, ROLES.STAFF];
export const PATIENT_CREATION_ROLES = [ROLES.SECRETARY, ROLES.STAFF];
export const PATIENT_APPROVAL_ROLES = [
  ROLES.ADMIN,
  ROLES.DOCTOR,
  ROLES.SECRETARY,
  ROLES.STAFF,
];
export const ADMIN_ONLY = [ROLES.ADMIN];
export const APPOINTMENT_CREATION_ROLES = [
  ROLES.DOCTOR,
  ROLES.SECRETARY,
  ROLES.STAFF,
];
export const APPOINTMENT_EDIT_ROLES = [
  ROLES.DOCTOR,
  ROLES.SECRETARY,
  ROLES.STAFF,
];
